theme: jekyll-theme-cayman

title: Unofficial Last Year: The Nightmare Guide
subtitle: Written and edited by MimimiLalala#4058
description: Everything an East Sider needs to know to survive victoriously
github:
  page2: homework2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: updates.html
  page7: eastsiders.html
  page8: phase1.html
  page9: phase2.html
  page10: phase3.html
  page11: fedora.html
  
